
project_id = "qrodseazvxvrixnmzumf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[functions]
[functions.config]
enabled = true

[functions.paths]
value = ["supabase/functions"]
